// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4nzSRNxfJXFr8rgZQaBroRT5wb659soU',
    appId: '1:2651318298:web:c074b02c4f951eb039c9a3',
    messagingSenderId: '2651318298',
    projectId: 'messaging-850a0',
    authDomain: 'messaging-850a0.firebaseapp.com',
    storageBucket: 'messaging-850a0.firebasestorage.app',
    measurementId: 'G-6HDH22XZCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRt7DhH0lUdhusozee9nbmeGAolRNkFvY',
    appId: '1:2651318298:android:9a7b667527418dd739c9a3',
    messagingSenderId: '2651318298',
    projectId: 'messaging-850a0',
    storageBucket: 'messaging-850a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcRj-8rVwX0PZ86MZRsf68iifRsKXO7qc',
    appId: '1:2651318298:ios:1c1c185c2148e67f39c9a3',
    messagingSenderId: '2651318298',
    projectId: 'messaging-850a0',
    storageBucket: 'messaging-850a0.firebasestorage.app',
    iosBundleId: 'com.speedobroadband.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcRj-8rVwX0PZ86MZRsf68iifRsKXO7qc',
    appId: '1:2651318298:ios:1bbca1173acfde1939c9a3',
    messagingSenderId: '2651318298',
    projectId: 'messaging-850a0',
    storageBucket: 'messaging-850a0.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4nzSRNxfJXFr8rgZQaBroRT5wb659soU',
    appId: '1:2651318298:web:6b5ff33630a6ff3239c9a3',
    messagingSenderId: '2651318298',
    projectId: 'messaging-850a0',
    authDomain: 'messaging-850a0.firebaseapp.com',
    storageBucket: 'messaging-850a0.firebasestorage.app',
    measurementId: 'G-ZYZKYMB2R0',
  );

}