// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUa08cHvcPXDiyAeezvsn22nuA-hnuIAo',
    appId: '1:629498338780:web:b241a697644b080a99c319',
    messagingSenderId: '629498338780',
    projectId: 'messaging-84244',
    authDomain: 'messaging-84244.firebaseapp.com',
    storageBucket: 'messaging-84244.firebasestorage.app',
    measurementId: 'G-PELR6ETZ2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhl3k2ZCEiBBxAGWyPAMWkdjYhViH1_DY',
    appId: '1:629498338780:android:a2b0906885a9162c99c319',
    messagingSenderId: '629498338780',
    projectId: 'messaging-84244',
    storageBucket: 'messaging-84244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsPtfp1imJev9rping0c_vWXdCRl6wE2A',
    appId: '1:629498338780:ios:0a8eea0b1e96f94499c319',
    messagingSenderId: '629498338780',
    projectId: 'messaging-84244',
    storageBucket: 'messaging-84244.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsPtfp1imJev9rping0c_vWXdCRl6wE2A',
    appId: '1:629498338780:ios:0a8eea0b1e96f94499c319',
    messagingSenderId: '629498338780',
    projectId: 'messaging-84244',
    storageBucket: 'messaging-84244.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUa08cHvcPXDiyAeezvsn22nuA-hnuIAo',
    appId: '1:629498338780:web:f462093a1b4b8b6599c319',
    messagingSenderId: '629498338780',
    projectId: 'messaging-84244',
    authDomain: 'messaging-84244.firebaseapp.com',
    storageBucket: 'messaging-84244.firebasestorage.app',
    measurementId: 'G-LNPJE0K2ZB',
  );
}
